config/routes.rb
Hydradam::Application.routes.draw do

  namespace :admin do
    mount RailsAdmin::Engine => '/dashboard', :as => 'rails_admin'
  end

  root to: 'homepage#index'

  Blacklight.add_routes(self)
  HydraHead.add_routes(self)
  Hydra::BatchEdit.add_routes(self)

  devise_for :users
  
  # Metadata Templates routes (based partly on catalog routes)
  resources 'imported_metadata_manager', :only=>:index do
    collection do
      get 'page/:page', :action => :index
      get 'activity', :action => :activity, :as => :dashboard_activity
      get 'facet/:id', :action => :facet, :as => :dashboard_facet
    end
  end
  
  resources "imported_metadata_files", except:[:index] do
    member do
      post 'apply' 
    end
  end

  # This must be the very last route in the file because it has a catch all route for 404 errors.
  # This behavior seems to show up only in production mode.
  mount Sufia::Engine => '/'
end

app/controllers/imported_metadata_files_controller.rb
class ImportedMetadataFilesController < ApplicationController
  include Sufia::Noid # for normalize_identifier method
  prepend_before_filter :normalize_identifier
  load_and_authorize_resource :class => ImportedMetadata, :instance_name =>:imported_metadata

  # Blacklight-Based Query Support
  include Blacklight::SolrHelper
  include Blacklight::Configurable # comply with BL 3.7
  # This is needed as of BL 3.7
  self.copy_blacklight_config_from(CatalogController)
  # before_filter :default_query_to_calculated_filepath
  ImportedMetadataFilesController.solr_search_params_logic = [:default_query_to_calculated_filepath, :add_query_to_solr,:add_facet_fq_to_solr, :add_facetting_to_solr, :add_solr_fields_to_query, :add_paging_to_solr, :add_sorting_to_solr, :only_query_path]
  before_filter :query_matches, only: [:show]
  
  configure_blacklight do |config|
    config.add_facet_field "unarranged_ssim", :label => "Already Arranged?", :limit => 3
  end
  
  
  #show
  def show
  end
  
  #edit
  def edit
  end
  
  #destroy
  def destroy
    pid = @imported_metadata.noid
    @imported_metadata.destroy
    Sufia.queue.push(ContentDeleteEventJob.new(pid, current_user.user_key))
    redirect_to imported_metadata_manager_index_path, notice: render_to_string(:partial=>'generic_files/asset_deleted_flash', :locals => { :generic_file => @imported_metadata })
  end

  def update
    @imported_metadata.update_attributes(params[:imported_metadata])
    redirect_to imported_metadata_file_path(@imported_metadata), notice: "Template has been updated"
  end

  def apply
    @imported_metadata.apply_to = params[:imported_metadata][:apply_to]
    @imported_metadata.apply!
    redirect_to imported_metadata_manager_index_path, notice: "Template is now being applied"
  end
  
  private
  
  def query_matches
    (@matches_response, @matches) = get_search_results
    @filters = params[:f] || []
  end
  
  def only_query_path solr_parameters, user_parameters
    solr_parameters[:q] = "relative_path:\"#{solr_parameters[:q]}\" OR noid_tsi:\"#{solr_parameters[:q]}\""
  end
  
  def default_query_to_calculated_filepath solr_parameters, user_parameters
    user_parameters[:q] = @imported_metadata.match_files_with_path unless params[:q] && !params[:q].empty?
    # default to returning only unarranged
    # params[:f] = 
  end
  
  def blacklight_solr
    @solr ||=  RSolr.connect(blacklight_solr_config)
  end

  def blacklight_solr_config
    Blacklight.solr_config
  end
  
end

app/views/imported_metadata_files/_breadcrumbs.html.erb
<div class="breadcrumbs">
  <%
     crumbs = []
     crumbs << link_to('Home', root_path)
     crumbs << link_to('Back to Imported Metadata Manager', imported_metadata_manager_index_path)

     crumbs.each do |crumb| %>
       <% if crumb == crumbs.last %>
       <span class="active"> <%= crumb %>
       <% else %>
       <span> <%= crumb %> <span class="divider">/</span>
       <% end %>
       </span>
  <% end %>
</div><!-- /breadcrumbs -->

app/views/imported_metadata_files/_form.html.erb
<h2 class="non lower">Descriptions</h2>
<%= form_for @imported_metadata, url: imported_metadata_file_path(@imported_metadata.noid) do |f| %>
    <table class="table table-striped"><!-- class="verticalheadings"> -->
      <tbody>
        <% @imported_metadata.terms_for_editing.each do |term| %>
          <%= f.label term %>
          <% if [:description, :filenames].include? term %>
            <%= f.text_area term, :class => "input-large" %>
          <% else %>
            <%= f.text_field term, :class => "input-large" %>
          <% end %>
        <% end %>
      </tbody>
    </table> <!-- /verticalheadings -->
    <%= f.submit :class=>'btn btn-primary' %>
<% end %>

app/views/imported_metadata_files/_matching_files.html.erb
<%# convert class variable to a local variable if the local hasn't been set %>
<% imported_metadata = @imported_metadata unless imported_metadata  %>

    <h2 id="matching_files">Matching Files</h2>
    By default, files are matched based on the path implied by the <b>Drive Name</b> and <b>Folder Name</b> in the imported metadata.

    <h3>Candidate matches:</h3>
    <%= render partial: 'search_form'%>
    <%= render partial: 'sort_and_per_page', locals:{response: @matches_response, documents:@matches} %>
    <%= render partial:'matching_files_list', locals:{matching_files: @matches} %>
    <%#= render partial: 'catalog/results_pagination', locals:{response: @matches_response, documents:@matches} %>
    

app/views/imported_metadata_files/_matching_files_list.html.erb
  <div id="documents" class="clear">
    <% if @matches.empty? %>
    <table class="table table-striped">
      <tbody>
        <tr>
          <td>No results match.</td>
        </tr>        
      </tbody>
    </table>
    <% else %>
      <%= form_for @imported_metadata, url: apply_imported_metadata_file_path(@imported_metadata), method: :post do |f| %>
        <table class="table table-striped">
          <tbody>
            <% @matches.each do |m| %>
              <tr>
                <td><%= check_box_tag 'imported_metadata[apply_to][]', m.id %></td>
                <td><%= link_to raw('<i class="icon-file"></i> View File'), sufia.generic_file_path(m.noid), :class=> 'itemicon itemedit', :title => 'View File'  %></td>
                <td><%= m[:relative_path] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <div class="form-actions">
        <%= f.submit 'Apply Metadata to selected files', class: 'btn btn-primary' %>
      </div>
      <% end %>
    <% end %>
  </div>

app/views/imported_metadata_files/_search_form.html.erb
<div style="float: right;" >
  <%= form_for(@imported_metadata, url:imported_metadata_file_path(@imported_metadata, anchor:"matching_files") , :method => :get, :class => "well form-search") do |f| %>

      <label class="accessible-hidden">Search by file path</label>
      <%= text_field_tag :q, params[:q], :class => "filepath-query", :placeholder => "Search by file path", :size => '30', :type => "search", :id => "filepath_search" %>
      <%= hidden_field_tag :sort, params[:sort], :id => 'filepath_sort' %>
      <%= search_as_hidden_fields(:omit_keys => [:q, :sort, :qt, :page]).html_safe %>
      <button type="submit" class="btn btn-primary" id="filepath_submit"><i class="icon-search"></i> Search</button>
  <% end %>
</div>

app/views/imported_metadata_files/_show_descriptions.html.erb
<%# convert class variable to a local variable if the local hasn't been set %>
<% imported_metadata = @imported_metadata unless imported_metadata  %>

    <h2 class="non lower">Descriptions
      <% if can? :edit, @imported_metadata %>
        <span style='font-size: small; font-weight: normal'>
        (<%= link_to "Edit", edit_imported_metadata_file_path %>)
        </span>
      <%end %>
    </h2>
    <table class="table table-striped"><!-- class="verticalheadings"> -->
      <tbody>
        <% imported_metadata.terms_for_display.each do |term| %>
          <% if term == :description %>
            <tr>
              <th><%= get_label(:description) %></th>
              <td>
                  <div itemprop="name">
                    <pre>
                    <%= imported_metadata.description %>
                    </pre>
                  </div>
              </td>
            </tr>
          <% else %>
            <%= render_show_field_partial(term, generic_file: imported_metadata) %>
          <% end %>
        <% end %>
      </tbody>
    </table> <!-- /verticalheadings -->

app/views/imported_metadata_files/_sort_and_per_page.html.erb
    <%-# kind of hacky way to get this to work on catalog and folder controllers.  May be able to simple do {:action=>"index"} but I'm not sure -%>
    <%= form_tag imported_metadata_file_path(@imported_metadata, anchor:"matching_files"), :method => :get, :class => "well form-inline" do %>
  <div class="sorting">
      <%#= label_tag(:sort, "<strong>Sort by</strong> ".html_safe) %>
      <%#= select_tag(:sort, options_for_select(sort_fields, h(params[:sort])), :class => "input-medium") %>
      <%
        # hack for blacklight. Rails no longer lets helpers access controller instance variables. Fixed in blacklight 4.6.
        @response = response
      %>
      <%= render_pagination_info response, :entry_name=>'matching file' %>
      <% unless response.response['numFound'] < 2 %>
      <%= label_tag(:per_page) do %>
        <strong>Show</strong> <%= select_tag(:per_page, options_for_select(['10', '20', '50', '100', '250', '500'], h(params[:per_page])), :title => "Number of results to display per page", :class => "input-small")  %> per page
        <% end %>
      <%= search_as_hidden_fields(:omit_keys => [:per_page, :sort]) %>
      <button class="btn btn-primary"><i class="icon-refresh"></i> Refresh</button>
      <% end %>
  </div>
    <% end %>

app/views/imported_metadata_files/edit.html.erb
<h1>Edit Imported Metadata</h1>
<%= link_to raw('<i class="icon-eye"></i> Stop Editing'), imported_metadata_file_path(@imported_metadata.noid), :class=> 'itemicon', :title => 'Stop Editing'  %>
<%= render partial: "form" %>

app/views/imported_metadata_files/show.html.erb
<%#
Copyright © 2012 The Pennsylvania State University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
%>


<% content_for :js_head do  %>
  <% javascript_include_tag 'https://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4ff1d986721ebb24' %>
  <script type="text/javascript">
    var addthis_config = {"data_track_addressbar":true};
  </script>
<% end %>

<%= render :partial => 'breadcrumbs', locals: {imported_metadata: @imported_metadata} %>

<h1 class="lower"><%= @imported_metadata.item_title %></h1>

<div class="row">
  <div class="span40">
  </div>
  <div class="span2">&nbsp;</div>
  <div class="span68"><!-- class="column second"> -->
    <%= render partial: 'show_descriptions' %>
    <%= render partial: 'matching_files' %>
    <%#= render :partial => 'users/activity_log', :locals => {:events => @events} %>
  </div><!-- /columns second -->
</div> <!-- /columns two-b -->