config/routes.rb
Hydradam::Application.routes.draw do

  namespace :admin do
    mount RailsAdmin::Engine => '/dashboard', :as => 'rails_admin'
  end

  root to: 'homepage#index'

  Blacklight.add_routes(self)
  HydraHead.add_routes(self)
  Hydra::BatchEdit.add_routes(self)

  devise_for :users
  
  # Metadata Templates routes (based partly on catalog routes)
  resources 'imported_metadata_manager', :only=>:index do
    collection do
      get 'page/:page', :action => :index
      get 'activity', :action => :activity, :as => :dashboard_activity
      get 'facet/:id', :action => :facet, :as => :dashboard_facet
    end
  end
  
  resources "imported_metadata_files", except:[:index] do
    member do
      post 'apply' 
    end
  end

  # This must be the very last route in the file because it has a catch all route for 404 errors.
  # This behavior seems to show up only in production mode.
  mount Sufia::Engine => '/'
end

app/controllers/imported_metadata_manager_controller.rb
# Copyright © 2012 The Pennsylvania State University
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require 'blacklight/catalog'
class ImportedMetadataManagerController < ApplicationController
  include  Sufia::DashboardControllerBehavior

  include Blacklight::Configurable  
  self.copy_blacklight_config_from(CatalogController)
  
  configure_blacklight do |config|
    config.add_facet_field "is_part_of_ssim", :label => "Parents", :limit => 5
  end
  
  # This filters out objects that you want to exclude from search results. 
  # 
  # Currently Filtering out:
  #   * ImportedMetadata 
  #
  # @param solr_parameters the current solr parameters
  # @param user_parameters the current user-subitted parameters
  def exclude_unwanted_models(solr_parameters, user_parameters)
    solr_parameters[:fq] ||= []
    solr_parameters[:fq] << "-#{ActiveFedora::SolrService.solr_name("has_model", :symbol)}:\"info:fedora/afmodel:GenericFile\""
  end
  
end

app/views/imported_metadata_manager/_batch_edits_actions.html.erb
<li data-behavior="batch-edit-select-none" data-state="on"><a href="#"><i class="icon-ok"></i> Select None</a></li>
<li data-behavior="batch-edit-select-page" data-state="off"><a href="#"><i class=""></i> Select Current Page</a></li>

app/views/imported_metadata_manager/_document_list.html.erb
<% # container for all documents in index view -%>
<div id="documents" class="clear">
  <%= render :partial => 'imported_metadata_manager/_index_partials/default_group', :locals => {:docs => @response.docs.map { |x| SolrDocument.new(x) }, :facet_value => nil} %>
</div>

app/views/imported_metadata_manager/_facet_layout.html.erb
<%#
Copyright © 2012 The Pennsylvania State University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
%>

<li class="expandable_new  grey">
   <% id = facet_field.label.sub(" ","_")+"_db" %>

    <a class="accordion-toggle grey" data-toggle="collapse" data-parent="#facet_group" data-target="#collapse_<%= id%>">
      <%= facet_field.label %><i class="icon-chevron-right grey"></i>
    </a>

  <div id="collapse_<%= id%>" class="accordion-body collapse">
      <%= yield %>
  </div>
</li>

app/views/imported_metadata_manager/_facet_limit.html.erb
<%#
Copyright © 2012 The Pennsylvania State University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
%>

  <% paginator =    
      Blacklight::Solr::FacetPaginator.new(display_facet.items,        
        :limit => facet_limit_for(solr_field))
      %>
<ul class="slide-list">
  <% paginator.items.each do |item| -%>
    <li>
    <% if facet_in_params?( solr_field, item.value ) %>              
        <%= render_selected_facet_value(solr_field, item).split("(").join('(<small>').split(")").join("</small>)").html_safe %>              
      <% else %>              
        <%= render_facet_value(solr_field, item).split("(").join('(<small>').split(")").join("</small>)").html_safe %>              
    <% end -%>
    </li>
  <% end %>

  <% if(paginator.has_next?)  %>
    <li class="more_facets_link"><%= link_to 'more ' + facet_field.label.pluralize + '»', sufia.url_for(params.merge(:id => solr_field, :action=>"facet", :path_only=>true)), :class => "more_facets_link" %></li>
  <% end %>
</ul> <!-- /slide-list -->

app/views/imported_metadata_manager/_facets.html.erb
<%#
Copyright © 2012 The Pennsylvania State University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
%>

<% # main container for facets/limits menu -%>
<div>
  <%= link_to '<i class="icon-upload-alt"></i> Upload File(s)'.html_safe, sufia.new_generic_file_path, {:class => "btn btn-primary"}  %><br />
  <div class="row">&nbsp;</div>
  <h2>Browse By</h2>
  <ul class="nav nav-list" id="facets">
    <%= render_facet_partials %>
  </ul>
</div>

app/views/imported_metadata_manager/_search_form.html.erb
<%#
Copyright © 2012 The Pennsylvania State University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
%>

<div style="float: right;" >
    <%= form_tag imported_metadata_manager_index_path, :method => :get, :class => "well form-search" do %>
      <label class="accessible-hidden">Search Imported Metadata</label>
      <%= text_field_tag :q, params[:q], :class => "q", :placeholder => "Search Imported Metadata", :size => '30', :type => "search", :id => "dashboard_search" %>
      <%= hidden_field_tag :search_field, 'all_fields' %>
    <%= search_as_hidden_fields(:omit_keys => [:q, :search_field, :qt, :page]).html_safe %>
    <%# submit_tag 'Go', {:class=>'btn btn-primary', :id => "dashboard_submit"} %>
    <button type="submit" class="btn btn-primary" id="dashboard_submit">
      <i class="icon-search"></i> Go
    </button>
  <% end %>
</div>

app/views/imported_metadata_manager/_sort_and_per_page.html.erb
<%#
Copyright © 2012 The Pennsylvania State University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
%>

<div class="batch-info"> 
   <% session[:batch_edit_state] = "on" %>
    <%=batch_delete%> <%=batch_edit_continue("Edit Selected") %>   
	<% unless @response.response['numFound'] < 2 %>
	  <%-# kind of hacky way to get this to work on catalog and folder controllers.  May be able to simple do {:action=>"index"} but I'm not sure -%>
    <%= form_tag imported_metadata_manager_index_path, :method=>:get, :class=>'per_page form-inline' do %>
      <%= label_tag(:sort, "<span>Sort By:</span>".html_safe) %>
      <%= select_tag(:sort, options_for_select(sort_fields, h(params[:sort])), :class => "span15") %>			      
      &nbsp;&nbsp;&nbsp;
      <%= label_tag(:per_page) do %>
        Show <%= select_tag(:per_page, options_for_select(['10', '20', '50', '100'], h(params[:per_page])), :title => "Number of results to display per page", :class => "span10") %> per page
        <% end %>
        <%= search_as_hidden_fields(:omit_keys => [:per_page, :sort]) %>
        &nbsp;&nbsp;&nbsp;
        <button class="btn btn-primary"><i class="icon-refresh"></i> Refresh</button>
		<% end unless sort_fields.empty? %>
  <% end %>
</div>

app/views/imported_metadata_manager/index.html.erb
<%#
Copyright © 2012 The Pennsylvania State University

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
%>

<% content_for :local_js do %>

  initialize_audio();

  function getSingleUse(id) {
    <% rurl = root_url %>
    <% rurl = rurl.slice(0, rurl.length-1) if rurl[rurl.length-1] == "/" %>
    var resp = $.ajax({
      headers: { Accept: "application/javascript" },
      type: 'get',
      url: "<%= rurl %>/single_use_link/generate_show/" + id.slice(10),
      async: false,
    });
    return "<%= rurl %>/" + resp.responseText;
  }

  // Load clipboard swf
  $(document).ready(function() {
    ZeroClipboard.setDefaults({ moviePath: "/assets/ZeroClipboard.swf" });
    $.each($(".copypaste"), function() {
      var clip = new ZeroClipboard();
      clip.on("dataRequested", function(client, args) {
        clip.setText(getSingleUse(this.id));
      })
      clip.on("complete", function(client, args) {
        alert("A single use link to " + args.text + " was copied to your clipboard.")
      })
      clip.on("noflash", function(client, args) {
        alert("Your single-use link: " + getSingleUse(this.id))
      })
      clip.on("wrongflash", function(client, args) {
        alert("Your single-use link: " + getSingleUse(this.id))
      })
      clip.glue($("#" + this.id))
    })
  });

  // hide or show the batch update buttons on page startup
  window.batch_part_on_other_page = <%= @batch_part_on_other_page%>;
  window.batch_size_on_other_page = <%= @batch_size_on_other_page%>;
  window.result_set_size = <%= @result_set_size%>;
  window.document_list_count = <%= @document_list.count %>;
  toggleButtons(<%= !@empty_batch %>);

  // initialize hydra batch edit and set up select all button toggle after checkboxes have been created
  $('#documents').batchEdit({afterCheckboxUpdate: setup_buttontoggle});


 <% end %>


  <% @page_title = application_name + " Imported Metadata Manager" %>

  <div class="accessible-hidden" id="current_user"><%=@user.user_key%></div>
  <div class="row">
    <%= render :partial => 'imported_metadata_manager/search_form' %>
    <h2 class="heading1">Imported Metadata Manager</h2>
  </div>

  <% extra_head_content << render_opensearch_response_metadata.html_safe %>
  <% if params.has_key?("q") %>
    <div class="alert alert-info"><i class="icon-search icon-large"></i> You searched for: <strong><%= params[:q] %></strong></div>
  <% end %>

  <%= render :partial => 'dashboard/did_you_mean' %>
  <%= render :partial => 'dashboard/facet_selected' %>

	<%= render 'dashboard/constraints', :localized_params=>params %>
  
  <% render_pagination_info @response, :entry_name=>'item' %>

  <%= render 'sort_and_per_page' %>

  <%= render :partial=>'imported_metadata_manager/document_list'  %>  
	<% content_for :sidebar do %>
	  <%= render :partial=>'imported_metadata_manager/facets' %>
	<%  end %>