config/routes.rb
Hydradam::Application.routes.draw do

  namespace :admin do
    mount RailsAdmin::Engine => '/dashboard', :as => 'rails_admin'
  end

  root to: 'homepage#index'

  Blacklight.add_routes(self)
  HydraHead.add_routes(self)
  Hydra::BatchEdit.add_routes(self)

  devise_for :users
  
  # Metadata Templates routes (based partly on catalog routes)
  resources 'imported_metadata_manager', :only=>:index do
    collection do
      get 'page/:page', :action => :index
      get 'activity', :action => :activity, :as => :dashboard_activity
      get 'facet/:id', :action => :facet, :as => :dashboard_facet
    end
  end
  
  resources "imported_metadata_files", except:[:index] do
    member do
      post 'apply' 
    end
  end

  # This must be the very last route in the file because it has a catch all route for 404 errors.
  # This behavior seems to show up only in production mode.
  mount Sufia::Engine => '/'
end

app/controllers/imported_metadata_manager_controller.rb
# Copyright © 2012 The Pennsylvania State University
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require 'blacklight/catalog'
class ImportedMetadataManagerController < ApplicationController
  include  Sufia::DashboardControllerBehavior

  include Blacklight::Configurable  
  self.copy_blacklight_config_from(CatalogController)
  
  configure_blacklight do |config|
    config.add_facet_field "is_part_of_ssim", :label => "Parents", :limit => 5
  end
  
  # This filters out objects that you want to exclude from search results. 
  # 
  # Currently Filtering out:
  #   * ImportedMetadata 
  #
  # @param solr_parameters the current solr parameters
  # @param user_parameters the current user-subitted parameters
  def exclude_unwanted_models(solr_parameters, user_parameters)
    solr_parameters[:fq] ||= []
    solr_parameters[:fq] << "-#{ActiveFedora::SolrService.solr_name("has_model", :symbol)}:\"info:fedora/afmodel:GenericFile\""
  end
  
end

app/views/imported_metadata_manager/_index_partials/_default_group.html.erb
<table class="table table-striped dashboard">
  <caption class="accessible-hidden">Listing of files you have deposited in <%= t('sufia.product_name') %></caption>
<% unless params[:display_type] == 'list' %>
  <thead> 
  <tr>
    <th class="sm"><%= render :partial => 'batch_edits/check_all' %></th>
    <th>&nbsp;</th>
    <th class="center">Series Title</th>
    <th class="center">Program Title</th>
    <th class="center">Item Title</th>
    <th class="center">Drive Name</th>
    <th class="center">Folder Name</th>
    <th class="center">Action</th>
  </tr>
  </thead> 
  <% end %>
  <tbody> 
  <% docs.each_with_index do |document,counter| %>
    <% if document["active_fedora_model_ssi"] == "GenericFile" %>
      <%= render :partial => 'dashboard/_index_partials/list_files', :locals => {:document => document, :counter => counter} %>
    <% elsif document["active_fedora_model_ssi"] == "ImportedMetadata" %>
      <%#= document.inspect%>
      <%= render :partial => 'imported_metadata_manager/_index_partials/imported_metadata', :locals => {:document => document, :counter => counter} %>
    <% else %>
    <% end %>
  <% end %>
  </tbody> 
</table>

app/views/imported_metadata_manager/_index_partials/_imported_metadata.html.erb
<% noid = document.noid %>
<tr id="document_<%= noid %>" class="<%= cycle("","zebra") %>">
  <% imported_metadata = ImportedMetadata.load_instance_from_solr(document.id) %>
  <td width="6%"><%= batch_edit_select(document) %>&nbsp;</td>
  <td width="1%">
  </td>
  <td width="37%">
    <span class=center>
    <%= link_to imported_metadata_file_path(imported_metadata.noid), :id => "src_copy_link#{noid}" do %>
      <%= render_index_field_value document, :field => 'series_title_tesim' %><br>
      <%= render_index_field_value document, :field => 'episode_title_tesim' %><br>
    <% end %> <br /></span>
  </td>
  <td>
    <%= link_to render_index_field_value(document, :field => 'program_title_tesim'), imported_metadata_file_path(imported_metadata.noid),  :id => "src_copy_link#{noid}" %>    
  </td>
  <td>
    <%= link_to render_index_field_value(document, :field => 'item_title_tesim'), imported_metadata_file_path(imported_metadata.noid),  :id => "src_copy_link#{noid}" %>
  </td>
  <td width="17%"><%= render_index_field_value(document, :field => 'drive_name_tesim') %> </td>

  <td width="17%"><%= render_index_field_value(document, :field => 'folder_name_tesim')%> </td>

  <td width="5%" align="center">
    <%# visibility %>
  </td>
  <td width="23%">
    <div class="btn-group">
      <button class="btn btn-small" href="#"><i class="icon-wrench"></i> Select an action</button>
      <button class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#"><span class="icon-caret-down"></span></button>
      <ul class="dropdown-menu">
       <li>
         <%= link_to raw('<i class="icon-pencil"></i> Edit Metadata Record'), edit_imported_metadata_file_path(imported_metadata.noid), :class=> 'itemicon itemedit', :title => 'Edit Metadata Record'  %>
       </li>
       <li>
         <%= link_to raw('<i class="icon-trash"></i> Delete Metadata Record'), imported_metadata_file_path(imported_metadata.noid), :class=> 'itemicon itemtrash', :title => 'Delete Metadata Record', :method => :delete, :data => { :confirm => "Deleting a file from #{t('sufia.product_name')} is permanent. Click OK to delete this file from #{t('sufia.product_name')}, or Cancel to cancel this operation"} %>
       </li>
      </ul>
    </div>
  </td>
</tr>
<tr class="hide" id="detail_<%= noid %>"> <!--  document detail"> -->
  <td colspan="6">
    <table class="expanded-details">
      <tr>
        
      </tr>
      <tr>
        <td><strong>Creator: </strong> <%= document.creator %> </td>
        <td><strong>Depositor: </strong> <%= link_to_profile document.depositor %> </td>
      </tr>
      <tr>
        <td colspan="2"><strong>Edit Access: </strong>
          <% if document.edit_groups.present? %>
            Groups: <%= document.edit_groups.join(', ') %>
            <br />
          <% end %>
          Users: <%= document.edit_people.join(', ') %>
        </td>
      </tr>
    </table>
  </td>
</tr>